
package es.gob.afirma.signfolder.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MobileService", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:v2.0")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MobileService {


    /**
     * 
     * @param initPage
     * @param signFormats
     * @param pageSize
     * @param state
     * @param filters
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileRequestList
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "requestList", targetNamespace = "")
    @RequestWrapper(localName = "queryRequestList", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.QueryRequestList")
    @ResponseWrapper(localName = "queryRequestListResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.QueryRequestListResponse")
    public MobileRequestList queryRequestList(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "state", targetNamespace = "")
        String state,
        @WebParam(name = "initPage", targetNamespace = "")
        String initPage,
        @WebParam(name = "pageSize", targetNamespace = "")
        String pageSize,
        @WebParam(name = "signFormats", targetNamespace = "")
        MobileStringList signFormats,
        @WebParam(name = "filters", targetNamespace = "")
        MobileRequestFilterList filters)
        throws MobileException
    ;

    /**
     * 
     * @param requestId
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileRequest
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "request", targetNamespace = "")
    @RequestWrapper(localName = "queryRequest", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.QueryRequest")
    @ResponseWrapper(localName = "queryRequestResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.QueryRequestResponse")
    public MobileRequest queryRequest(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId)
        throws MobileException
    ;

    /**
     * 
     * @param documentId
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileDocument
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "document", targetNamespace = "")
    @RequestWrapper(localName = "documentPreview", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.DocumentPreview")
    @ResponseWrapper(localName = "documentPreviewResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.DocumentPreviewResponse")
    public MobileDocument documentPreview(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId)
        throws MobileException
    ;

    /**
     * 
     * @param requestTagId
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileDocumentList
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "documentList", targetNamespace = "")
    @RequestWrapper(localName = "getDocumentsToSign", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.GetDocumentsToSign")
    @ResponseWrapper(localName = "getDocumentsToSignResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.GetDocumentsToSignResponse")
    public MobileDocumentList getDocumentsToSign(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "requestTagId", targetNamespace = "")
        String requestTagId)
        throws MobileException
    ;

    /**
     * 
     * @param docSignInfoList
     * @param certificate
     * @param requestTagId
     * @return
     *     returns java.lang.String
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "saveSign", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.SaveSign")
    @ResponseWrapper(localName = "saveSignResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.SaveSignResponse")
    public String saveSign(
        @WebParam(name = "certificate", targetNamespace = "")
        byte[] certificate,
        @WebParam(name = "requestTagId", targetNamespace = "")
        String requestTagId,
        @WebParam(name = "docSignInfoList", targetNamespace = "")
        MobileDocSignInfoList docSignInfoList)
        throws MobileException
    ;

    /**
     * 
     * @param textRejection
     * @param requestId
     * @param dni
     * @return
     *     returns java.lang.String
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "responseId", targetNamespace = "")
    @RequestWrapper(localName = "rejectRequest", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.RejectRequest")
    @ResponseWrapper(localName = "rejectRequestResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.RejectRequestResponse")
    public String rejectRequest(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "textRejection", targetNamespace = "")
        String textRejection)
        throws MobileException
    ;

    /**
     * 
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileApplicationList
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "applicationList", targetNamespace = "")
    @RequestWrapper(localName = "queryApplicationsMobile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.QueryApplicationsMobile")
    @ResponseWrapper(localName = "queryApplicationsMobileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.QueryApplicationsMobileResponse")
    public MobileApplicationList queryApplicationsMobile(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni)
        throws MobileException
    ;

    /**
     * 
     * @param requestTagId
     * @param dni
     * @return
     *     returns java.lang.String
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "responseId", targetNamespace = "")
    @RequestWrapper(localName = "approveRequest", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.ApproveRequest")
    @ResponseWrapper(localName = "approveRequestResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.ApproveRequestResponse")
    public String approveRequest(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "requestTagId", targetNamespace = "")
        String requestTagId)
        throws MobileException
    ;

    /**
     * 
     * @param documentId
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileDocument
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "document", targetNamespace = "")
    @RequestWrapper(localName = "signPreview", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.SignPreview")
    @ResponseWrapper(localName = "signPreviewResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.SignPreviewResponse")
    public MobileDocument signPreview(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId)
        throws MobileException
    ;

    /**
     * 
     * @param documentId
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileDocument
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "document", targetNamespace = "")
    @RequestWrapper(localName = "reportPreview", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.ReportPreview")
    @ResponseWrapper(localName = "reportPreviewResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.ReportPreviewResponse")
    public MobileDocument reportPreview(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId)
        throws MobileException
    ;

    /**
     * 
     * @param dni
     * @param register
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileSIMUserStatus
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "registerStatus", targetNamespace = "")
    @RequestWrapper(localName = "registerSIMUser", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.RegisterSIMUser")
    @ResponseWrapper(localName = "registerSIMUserResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.RegisterSIMUserResponse")
    public MobileSIMUserStatus registerSIMUser(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "register", targetNamespace = "")
        MobileSIMUser register)
        throws MobileException
    ;

    /**
     * 
     * @param certificate
     * @return
     *     returns java.lang.String
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "nifCif", targetNamespace = "")
    @RequestWrapper(localName = "validateUser", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.ValidateUser")
    @ResponseWrapper(localName = "validateUserResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.ValidateUserResponse")
    public String validateUser(
        @WebParam(name = "certificate", targetNamespace = "")
        byte[] certificate)
        throws MobileException
    ;

    /**
     * 
     * @param estadoNotifyPush
     * @param dni
     * @return
     *     returns java.lang.String
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "updateNotifyPush", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.UpdateNotifyPush")
    @ResponseWrapper(localName = "updateNotifyPushResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.UpdateNotifyPushResponse")
    public String updateNotifyPush(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "estadoNotifyPush", targetNamespace = "")
        String estadoNotifyPush)
        throws MobileException
    ;

    /**
     * 
     * @param dni
     * @return
     *     returns java.lang.String
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "valorNotifyPush", targetNamespace = "")
    @RequestWrapper(localName = "estadoNotifyPush", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.EstadoNotifyPush")
    @ResponseWrapper(localName = "estadoNotifyPushResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.EstadoNotifyPushResponse")
    public String estadoNotifyPush(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni)
        throws MobileException
    ;

    /**
     * 
     * @param spReturn
     * @param spUrl
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileAccesoClave
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "solicitudAccesoClaveRespuesta", targetNamespace = "")
    @RequestWrapper(localName = "solicitudAccesoClave", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.SolicitudAccesoClave")
    @ResponseWrapper(localName = "solicitudAccesoClaveResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.SolicitudAccesoClaveResponse")
    public MobileAccesoClave solicitudAccesoClave(
        @WebParam(name = "spUrl", targetNamespace = "")
        String spUrl,
        @WebParam(name = "spReturn", targetNamespace = "")
        String spReturn)
        throws MobileException
    ;

    /**
     * 
     * @param remoteHost
     * @param samlresponse
     * @return
     *     returns java.lang.String
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "nifCif", targetNamespace = "")
    @RequestWrapper(localName = "procesarRespuestaClave", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.ProcesarRespuestaClave")
    @ResponseWrapper(localName = "procesarRespuestaClaveResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.ProcesarRespuestaClaveResponse")
    public String procesarRespuestaClave(
        @WebParam(name = "samlresponse", targetNamespace = "")
        String samlresponse,
        @WebParam(name = "remoteHost", targetNamespace = "")
        String remoteHost)
        throws MobileException
    ;

    /**
     * 
     * @param idRequestList
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileFireTrasactionResponse
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "fireTransactionResponse", targetNamespace = "")
    @RequestWrapper(localName = "fireTransaction", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.FireTransaction")
    @ResponseWrapper(localName = "fireTransactionResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.FireTransactionResponse")
    public MobileFireTrasactionResponse fireTransaction(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "idRequestList", targetNamespace = "")
        MobileStringList idRequestList)
        throws MobileException
    ;

    /**
     * 
     * @param idRequestList
     * @param dni
     * @param transactionId
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileFireRequestList
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "fireRequestList", targetNamespace = "")
    @RequestWrapper(localName = "signFireCloud", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.SignFireCloud")
    @ResponseWrapper(localName = "signFireCloudResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.SignFireCloudResponse")
    public MobileFireRequestList signFireCloud(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "idRequestList", targetNamespace = "")
        MobileStringList idRequestList,
        @WebParam(name = "transactionId", targetNamespace = "")
        String transactionId)
        throws MobileException
    ;

    /**
     * 
     * @param dniValidador
     * @param requestTagId
     * @return
     *     returns java.lang.String
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "validarPeticion", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.ValidarPeticion")
    @ResponseWrapper(localName = "validarPeticionResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.ValidarPeticionResponse")
    public String validarPeticion(
        @WebParam(name = "dniValidador", targetNamespace = "")
        byte[] dniValidador,
        @WebParam(name = "requestTagId", targetNamespace = "")
        String requestTagId)
        throws MobileException
    ;

    /**
     * 
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileConfiguracionUsuario
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "mobileConfiguracionUsuario", targetNamespace = "")
    @RequestWrapper(localName = "configuracionUsuarioMobile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.ConfiguracionUsuarioMobile")
    @ResponseWrapper(localName = "configuracionUsuarioMobileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.ConfiguracionUsuarioMobileResponse")
    public MobileConfiguracionUsuario configuracionUsuarioMobile(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni)
        throws MobileException
    ;

    /**
     * 
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileAutorizacionesList
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "autorizacionesList", targetNamespace = "")
    @RequestWrapper(localName = "recuperarAutorizaciones", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.RecuperarAutorizaciones")
    @ResponseWrapper(localName = "recuperarAutorizacionesResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.RecuperarAutorizacionesResponse")
    public MobileAutorizacionesList recuperarAutorizaciones(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni)
        throws MobileException
    ;

    /**
     * 
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileTiposAutorizacionList
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "tiposAutorizacionesList", targetNamespace = "")
    @RequestWrapper(localName = "tiposAutorizacion", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.TiposAutorizacion")
    @ResponseWrapper(localName = "tiposAutorizacionResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.TiposAutorizacionResponse")
    public MobileTiposAutorizacionList tiposAutorizacion(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni)
        throws MobileException
    ;

    /**
     * 
     * @param filtroBusqueda
     * @param modoBusqueda
     * @param parametros
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileUsuariosList
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "mobileUsuariosList", targetNamespace = "")
    @RequestWrapper(localName = "busquedaUsuariosMobile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.BusquedaUsuariosMobile")
    @ResponseWrapper(localName = "busquedaUsuariosMobileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.BusquedaUsuariosMobileResponse")
    public MobileUsuariosList busquedaUsuariosMobile(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "filtroBusqueda", targetNamespace = "")
        String filtroBusqueda,
        @WebParam(name = "modoBusqueda", targetNamespace = "")
        String modoBusqueda,
        @WebParam(name = "parametros", targetNamespace = "")
        MobileParameterList parametros)
        throws MobileException
    ;

    /**
     * 
     * @param mobileAutorizacion
     * @return
     *     returns java.lang.String
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "salvarAutorizacionMobile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.SalvarAutorizacionMobile")
    @ResponseWrapper(localName = "salvarAutorizacionMobileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.SalvarAutorizacionMobileResponse")
    public String salvarAutorizacionMobile(
        @WebParam(name = "mobileAutorizacion", targetNamespace = "")
        MobileAutorizacion mobileAutorizacion)
        throws MobileException
    ;

    /**
     * 
     * @param accion
     * @param dni
     * @param idAutorizacion
     * @return
     *     returns java.lang.String
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "cambiarEstadoAutorizacionMobile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.CambiarEstadoAutorizacionMobile")
    @ResponseWrapper(localName = "cambiarEstadoAutorizacionMobileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.CambiarEstadoAutorizacionMobileResponse")
    public String cambiarEstadoAutorizacionMobile(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "accion", targetNamespace = "")
        String accion,
        @WebParam(name = "idAutorizacion", targetNamespace = "")
        String idAutorizacion)
        throws MobileException
    ;

    /**
     * 
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileApplicationList
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "mobileApplicationList", targetNamespace = "")
    @RequestWrapper(localName = "aplicacionesParaValidarMobile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.AplicacionesParaValidarMobile")
    @ResponseWrapper(localName = "aplicacionesParaValidarMobileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.AplicacionesParaValidarMobileResponse")
    public MobileApplicationList aplicacionesParaValidarMobile(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni)
        throws MobileException
    ;

    /**
     * 
     * @param dni
     * @return
     *     returns es.gob.afirma.signfolder.client.MobileValidadorList
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "mobileValidadorList", targetNamespace = "")
    @RequestWrapper(localName = "recuperarValidadoresMobile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.RecuperarValidadoresMobile")
    @ResponseWrapper(localName = "recuperarValidadoresMobileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.RecuperarValidadoresMobileResponse")
    public MobileValidadorList recuperarValidadoresMobile(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni)
        throws MobileException
    ;

    /**
     * 
     * @param primaryKeyValidador
     * @param dni
     * @return
     *     returns java.lang.String
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "eliminarValidadorMobile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.EliminarValidadorMobile")
    @ResponseWrapper(localName = "eliminarValidadorMobileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.EliminarValidadorMobileResponse")
    public String eliminarValidadorMobile(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "primaryKeyValidador", targetNamespace = "")
        String primaryKeyValidador)
        throws MobileException
    ;

    /**
     * 
     * @param accion
     * @param validador
     * @param dni
     * @return
     *     returns java.lang.String
     * @throws MobileException
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "salvarValidadorMobile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.SalvarValidadorMobile")
    @ResponseWrapper(localName = "salvarValidadorMobileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:request:v2.0", className = "es.gob.afirma.signfolder.client.SalvarValidadorMobileResponse")
    public String salvarValidadorMobile(
        @WebParam(name = "dni", targetNamespace = "")
        byte[] dni,
        @WebParam(name = "validador", targetNamespace = "")
        MobileValidador validador,
        @WebParam(name = "accion", targetNamespace = "")
        String accion)
        throws MobileException
    ;

}
