
package es.gob.afirma.signfolder.client;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "MobileService", targetNamespace = "urn:juntadeandalucia:cice:pfirma:mobile:v2.0", wsdlLocation = "https://pf.seap.minhap.es/pf/servicesv2/MobileService?wsdl")
public class MobileService_Service
    extends Service
{
    /** Construye el servicio.
     * @param wsdlLocation Localizacion del servlet.
     * @param serviceName Nombre del servicio.
     */
    public MobileService_Service(final URL wsdlLocation, final QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /** Contruye el servicio.
     * @param wsdlLocation URL del WSDL del servicio. */
    public MobileService_Service(final URL wsdlLocation) {
    	super(wsdlLocation, new QName("urn:juntadeandalucia:cice:pfirma:mobile:v2.0", "MobileService")); //$NON-NLS-1$ //$NON-NLS-2$
    }

    /**
     *
     * @return
     *     returns MobileService
     */
    @WebEndpoint(name = "MobileServicePort")
    public MobileService getMobileServicePort() {
        return super.getPort(new QName("urn:juntadeandalucia:cice:pfirma:mobile:v2.0", "MobileServicePort"), MobileService.class); //$NON-NLS-1$ //$NON-NLS-2$
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileService
     */
    @WebEndpoint(name = "MobileServicePort")
    public MobileService getMobileServicePort(final WebServiceFeature... features) {
        return super.getPort(new QName("urn:juntadeandalucia:cice:pfirma:mobile:v2.0", "MobileServicePort"), MobileService.class, features); //$NON-NLS-1$ //$NON-NLS-2$
    }

}
